cleared: [255188888400822272, 260278740162969611]
cogs: [cogs.core, cogs.mod, cogs.misc, cogs.fun, cogs.dev, cogs.economy, cogs.utility]
token: NDA1MjMxNTg1MDUxNDEwNDQy.DUhY2Q.WqFzm_weRWsV6tweG0hUN_ug_bo
genius_token: nnFTYsS1qBk3VkESVtldaA5ocGe73lgbt9we3inTw2nsJFZ2jB8rQAoCZNMeYWLm
